fix: improve the some details in the deploy action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,20 +1,31 @@
 name: TrackMoney Pipeline
 
 on:
-  push:
+  workflow_run:
+    workflows: ["SonarCloud CI"]
+    types:
+      - completed
     branches:
       - main
-  pull_request:
-    branches:
-      - main
+  workflow_dispatch:
 
 env:
   APP_NAME: trackmoney
 
 jobs:
+  check-previous-workflow:
+    runs-on: ubuntu-latest
+    if: github.event.workflow_run.conclusion != 'success'
+    steps:
+      - name: Previous workflow failed
+        run: |
+          echo "❌ Previous workflow (SonarCloud CI) failed or was cancelled"
+          exit 1
+
   tests:
     runs-on: ubuntu-latest
     name: Tests
+    if: github.event.workflow_run.conclusion == 'success'
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -41,7 +52,7 @@ jobs:
     runs-on: ubuntu-latest
     name: Build & Push
     needs: tests
-    if: github.ref == 'refs/heads/main'
+    if: github.event.workflow_run.head_branch == 'main'
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
